// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getSupabaseEnv() {
  const runtimeEnv = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env;

  return {
    url:
      runtimeEnv?.VITE_SUPABASE_URL ??
      runtimeEnv?.SUPABASE_URL ??
      process.env.SUPABASE_URL ??
      process.env.VITE_SUPABASE_URL,
    publishableKey:
      runtimeEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ??
      runtimeEnv?.SUPABASE_PUBLISHABLE_KEY ??
      process.env.SUPABASE_PUBLISHABLE_KEY ??
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  };
}

function createMissingSupabaseClient() {
  const message =
    "Supabase is not configured yet. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment to enable authentication.";
  const error = new Error(message);

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error }),
      getUser: async () => ({ data: { user: null }, error }),
      signUp: async () => ({ data: { user: null, session: null }, error }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error }),
      signInWithOAuth: async () => ({ data: null, error }),
      signOut: async () => ({ error }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
      getClaims: async () => ({ data: null, error }),
      setSession: async () => ({ data: { user: null, session: null }, error }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  const { url, publishableKey } = getSupabaseEnv();

  if (!url || !publishableKey) {
    const missing = [
      ...(url ? [] : ["SUPABASE_URL / VITE_SUPABASE_URL"]),
      ...(publishableKey ? [] : ["SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY"]),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set the Supabase environment variables before using auth.`;
    console.warn(`[Supabase] ${message}`);
    return createMissingSupabaseClient();
  }

  return createClient<Database>(url, publishableKey, {
    global: {
      fetch: createSupabaseFetch(publishableKey),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
